version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Pre-build phase"
      - chmod +x gradlew
  build:
    commands:
      - echo "Build phase"
      - ./gradlew build
artifacts:
  type: codepipeline
  files:
    - app.jar
    - plain.jar
  name: MyOutputArtifact
