version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Pre-build phase"
      - chmod +x gradlew
  build:
    commands:
      - echo "Build phase"
      - ./gradlew build
artifacts:
  type: codepipeline
  files:
    - build/libs/*.jar
  name: MyOutputArtifact
  discard-paths: yes
  base-directory: build/libs
  secondary-artifacts:
    AdditionalArtifact:
      type: codepipeline
      files:
        - '*.jar'
      base-directory: build/libs
