version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Pre-build phase"
      - chmod +x gradlew
  build:
    commands:
      - echo "Building the application..."
      - chmod +x gradlew && ./gradlew build
  post_build:
    commands:
      - echo "Packaging the application"
      - ls build/libs/
      - mkdir -p target
      - find build/libs/ -name '*.jar' -exec cp {} target/app.jar \;
artifacts:
  type: codepipeline
  files:
    - target/app.jar
  discard-paths: yes
