version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Building the application...
      - chmod +x gradlew && ./gradlew build
artifacts:
  type: codepipeline
  files:
    - 'build/libs/*.jar'
  name: my-application
