version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Pre-build phase"
      - chmod +x gradlew
  build:
    commands:
      - echo "Build phase"
      - ./gradlew build
  post_build:
    commands:
      - echo "Post-build phase"
      - mv build/libs/kotlinrest-0.0.1-SNAPSHOT.jar kotlinrest-0.0.1-SNAPSHOT.jar

artifacts:
  type: codepipeline
  files:
    - kotlinrest-0.0.1-SNAPSHOT.jar # Adjust this path based on your build output directory
