version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Pre-build phase"
      - chmod +x gradlew
  build:
    commands:
      - echo Building the application...
      - chmod +x gradlew && ./gradlew build
artifacts:
  type: codepipeline
  files:
    - 'build/libs/*.jar'
  name: kotlinrest-0.0.1-snapshot
  namespace_type: 1
